### ISSUE TITLE
cannot build/install

### ISSUE THREAD

**Issue by th3w1zard1** [markferry/multizone-audio#1]
How in the world do you install this? Running make gives the error

`~/multizone-audio$ make
make: *** No rule to make target '/home/<user>/.venvs/chevron/bin/chevron', needed by '../snapserver.conf'.  Stop.`

Big admirer of the dedication and effort you've put into getting this project working the way you wanted it.

**Comment by markferry** [comment]
Ah, as you've noticed I haven't added any build instructions yet. (There are still have a bunch of hardcoded paths I haven't abstracted yet).

But to get you back on track you need an install of [chevron](https://github.com/noahmorrison/chevron) - a very simple templating engine. I happen to have it in its own python virtual environment.

Something like this...
```bash
python3 -m venv ~/.venv/chevron
source ~/.venv/bin/activate
pip install chevron
```

chevron takes each template and merges in the variables from either the players.json or <room>.json files.

**Comment by markferry** [comment]
Updated the Makefile to install chevron in a python virtualenv if necessary.

Also added a Usage section to the [README](../blob/master/README.md).

Hope that helps.

**Comment by th3w1zard1** [comment]
I'd like to reiterate how blown away I am by your approach on this subject. Most people would just pay whatever to some tech giant to get something that would only work for 2years or however long they decide to host the cloud. Even going a step above that other people would continue using what they setup initially because they're already habitually used to how it works, but I've noticed you even dumped Volumio which a lot of other users are using for their setup. Snapcast-autoconfig is a nice touch. 

I'd very much like to install this with librespot-java, installed through https://github.com/spocon/spocon honestly that'll be a project I'll tackle after I get an actual initial setup going.

Shairport-sync now supports AirPlay2 in its beta version which will be a nice addition I believe.

Anyway I'll attempt a build in the next few hours and follow up here afterwards! Great work man.

**Comment by th3w1zard1** [comment]
I'm seriously surprised by how quickly you've been documenting & updating your project since I posted this issue. Hoping I've rekindled the flames of your enthusiasm for the project again? :)
More likely you're just updating the github page with more of your local info to help me and other users out. Either way I'm grateful; this is the biggest smart home project I've attempted to tackle. I've mostly just begun configuring zigbee devices up until this point.

> I originally had independent service unit files (see, for example librespot@.service.template), but dumped them for the simpler approach of having snapcast run stuff. That might have had something to do with metadata (which is incomplete #3).

Just to clarify, your below examples are showing the current implementation using snapcast metadata vs the librespot@.service.template?

I'm currently writing a bash script that will help pull all of these projects together so that if I want to at some point clean wipe with a fresh os I won't have to -completely- start from scratch. Will allow me flexibility to experiment with other alternative projects to ones listed (like spocon with librespot-java over librespot, etc).

`Could use process:// stream source, or Snapcast could maybe implement librespot-java://.`

Bad link but I found the link on my own here:
https://github.com/badaix/snapcast/issues/928

Cheers.

**Comment by th3w1zard1** [comment]
`Could use process:// stream source, or Snapcast could maybe implement librespot-java://.`

here's the link I believe you're trying to reference to help ya out
`https://github.com/badaix/snapcast/issues/928`

I will stay subscribed with the project.

Cheers mate,
